// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://civlhqtnmugaazjiiewd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpdmxocXRubXVnYWF6amlpZXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MTc1NzksImV4cCI6MjA2NDQ5MzU3OX0.lFVjjNEae5u7Cy8n4dhqXVjaj0SY1_X83c0OLF6VFFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);